### ISSUE TITLE
Clashes with xunitcontrib runner

### ISSUE THREAD

**Issue by citizenmatt** [hazzik/ReSharper.XUnitTestRunner#3]
Hi Hazzik. There's an issue if someone installs both this runner and the xunitcontrib runner, because they both share the same provider ID (e.g. http://youtrack.jetbrains.com/issue/RSPL-4951 - the xunitcontrib provider is trying to serialise the elements from this project). Could you update your code with a new ID, please?

Thanks
Matt

**Comment by hazzik** [comment]
Sure.
